# Generated by Django 5.1.7 on 2025-10-09 20:07

import core.models.hierarquicos
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('nivel', models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('diretor', 'Diretor')], default='analista', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('centro_custo', models.CharField(blank=True, help_text='Centro de custo do usuário', max_length=20, null=True)),
                ('unidade_negocio', models.CharField(blank=True, help_text='Unidade de negócio', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Centro de Custo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_pai', models.CharField(blank=True, help_text='Código do centro de custo superior na hierarquia (deixe vazio para raiz)', max_length=20, null=True, verbose_name='Código do Centro Pai')),
                ('tipo', models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', help_text='S=Sintético (agrupador), A=Analítico (operacional)', max_length=1, verbose_name='Tipo')),
                ('nivel', models.IntegerField(verbose_name='Nível Hierárquico')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Custo',
                'verbose_name_plural': 'Centros de Custo',
                'db_table': 'centros_custo',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='centros_cus_codigo_0e4605_idx'), models.Index(fields=['codigo_pai'], name='centros_cus_codigo__0a6f0d_idx'), models.Index(fields=['ativo'], name='centros_cus_ativo_91328b_idx'), models.Index(fields=['nivel'], name='centros_cus_nivel_d0d45a_idx'), models.Index(fields=['tipo'], name='centros_cus_tipo_d74add_idx')],
            },
            bases=(models.Model, core.models.hierarquicos.HierarchiaDeclaradaMixin),
        ),
        migrations.CreateModel(
            name='ContaContabil',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('codigo_pai', models.CharField(blank=True, help_text='Código da conta contábil superior na hierarquia (deixe vazio para raiz)', max_length=20, null=True, verbose_name='Código da Conta Pai')),
                ('tipo', models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', help_text='S=Sintético (agrupador), A=Analítico (aceita lançamentos)', max_length=1, verbose_name='Tipo')),
                ('nivel', models.IntegerField(verbose_name='Nível Hierárquico')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta Contábil',
                'verbose_name_plural': 'Contas Contábeis',
                'db_table': 'contas_contabeis',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['codigo'], name='contas_cont_codigo_c596a6_idx'), models.Index(fields=['codigo_pai'], name='contas_cont_codigo__1d7ddb_idx'), models.Index(fields=['ativa'], name='contas_cont_ativa_295a30_idx'), models.Index(fields=['nivel'], name='contas_cont_nivel_2efcbe_idx'), models.Index(fields=['tipo'], name='contas_cont_tipo_586c75_idx')],
            },
            bases=(models.Model, core.models.hierarquicos.HierarchiaDeclaradaMixin),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('sigla', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Sigla')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Estadual')),
                ('inscricao_municipal', models.CharField(blank=True, max_length=30, verbose_name='Inscrição Municipal')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('sincronizado_allstrategy', models.BooleanField(default=False, verbose_name='Sincronizado All Strategy')),
                ('data_ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
                'ordering': ['sigla'],
                'indexes': [models.Index(fields=['sigla'], name='empresas_sigla_c60b15_idx'), models.Index(fields=['cnpj'], name='empresas_cnpj_009d7f_idx'), models.Index(fields=['ativa'], name='empresas_ativa_ae071f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código')),
                ('razao_social', models.CharField(db_index=True, max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_automaticamente', models.BooleanField(default=False, verbose_name='Criado Automaticamente')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('origem_historico', models.TextField(blank=True, help_text='Histórico original de onde foi extraído', verbose_name='Histórico de Origem')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedores',
                'ordering': ['razao_social'],
                'indexes': [models.Index(fields=['codigo'], name='fornecedore_codigo_bb168c_idx'), models.Index(fields=['razao_social'], name='fornecedore_razao_s_c3008e_idx'), models.Index(fields=['ativo'], name='fornecedore_ativo_bee848_idx'), models.Index(fields=['criado_automaticamente'], name='fornecedore_criado__b52c13_idx'), models.Index(fields=['razao_social', 'ativo'], name='fornecedore_razao_s_c0d675_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParametroSistema',
            fields=[
                ('codigo', models.CharField(help_text='Código único do parâmetro', max_length=50, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('decimal', 'Decimal'), ('boolean', 'Verdadeiro/Falso'), ('data', 'Data'), ('json', 'JSON')], default='texto', max_length=20)),
                ('valor', models.TextField(help_text='Valor do parâmetro (será convertido conforme o tipo)', verbose_name='Valor')),
                ('valor_padrao', models.TextField(blank=True, verbose_name='Valor Padrão')),
                ('categoria', models.CharField(default='geral', help_text='Categoria para organização (ex: financeiro, sistema, etc)', max_length=50)),
                ('editavel', models.BooleanField(default=True, help_text='Se False, parâmetro não pode ser editado via interface')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parâmetro do Sistema',
                'verbose_name_plural': 'Parâmetros do Sistema',
                'db_table': 'parametros_sistema',
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Unidade')),
                ('codigo_pai', models.CharField(blank=True, help_text='Código da unidade superior na hierarquia (deixe vazio para raiz)', max_length=50, null=True, verbose_name='Código da Unidade Pai')),
                ('codigo_allstrategy', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Código All Strategy')),
                ('tipo', models.CharField(choices=[('S', 'Sintético'), ('A', 'Analítico')], default='A', max_length=1, verbose_name='Tipo')),
                ('nivel', models.IntegerField(verbose_name='Nível Hierárquico')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unidades', to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Unidade Organizacional',
                'verbose_name_plural': 'Unidades Organizacionais',
                'db_table': 'unidades',
                'ordering': ['codigo'],
            },
            bases=(models.Model, core.models.hierarquicos.HierarchiaDeclaradaMixin),
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data', models.DateField(db_index=True, verbose_name='Data do Movimento')),
                ('documento', models.CharField(blank=True, help_text='Número do documento', max_length=50, verbose_name='Documento')),
                ('natureza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito'), ('A', 'Ambas')], help_text='D=Débito, C=Crédito, A=Ambas', max_length=1, verbose_name='Natureza')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do movimento', max_digits=15, verbose_name='Valor')),
                ('historico', models.TextField(help_text='Histórico completo da movimentação', verbose_name='Histórico')),
                ('codigo_projeto', models.CharField(blank=True, max_length=20, verbose_name='Código do Projeto')),
                ('gerador', models.CharField(blank=True, help_text='Sistema ou processo que gerou o movimento', max_length=100, verbose_name='Gerador')),
                ('rateio', models.CharField(default='N', help_text='S=Sim, N=Não', max_length=1, verbose_name='Rateio')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('arquivo_origem', models.CharField(blank=True, help_text='Nome do arquivo Excel de origem', max_length=255, verbose_name='Arquivo de Origem')),
                ('linha_origem', models.IntegerField(blank=True, help_text='Linha no arquivo Excel de origem', null=True, verbose_name='Linha de Origem')),
                ('periodo_mes_ano', models.CharField(db_index=True, help_text='Formato YYYY-MM para indexação rápida', max_length=7, verbose_name='Período')),
                ('valor_absoluto', models.DecimalField(decimal_places=2, help_text='Valor sem sinal para totalizações', max_digits=15, verbose_name='Valor Absoluto')),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.centrocusto', verbose_name='Centro de Custo')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.contacontabil', verbose_name='Conta Contábil')),
                ('fornecedor', models.ForeignKey(blank=True, help_text='Fornecedor extraído do histórico (quando aplicável)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.fornecedor', verbose_name='Fornecedor')),
                ('unidade', models.ForeignKey(help_text='Unidade organizacional', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Movimento',
                'verbose_name_plural': 'Movimentos',
                'db_table': 'movimentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_com_acesso', to='core.centrocusto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo_permitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão Centro de Custo',
                'verbose_name_plural': 'Permissões Centros de Custo',
                'db_table': 'usuario_centros_custo',
            },
        ),
        migrations.CreateModel(
            name='ContaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(db_index=True, help_text='Código da conta no sistema externo (ERP)', max_length=50, verbose_name='Código Externo')),
                ('nome_externo', models.CharField(help_text='Nome/descrição da conta no sistema externo', max_length=255, verbose_name='Nome no Sistema Externo')),
                ('sistema_origem', models.CharField(blank=True, help_text='Nome do ERP/sistema de origem (ex: Consinco, Protheus)', max_length=100, verbose_name='Sistema de Origem')),
                ('empresas_utilizacao', models.TextField(blank=True, help_text='Empresas que utilizam esta conta (ex: CMC & EBC & Taiff & Action Motors)', verbose_name='Empresas de Utilização')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a conta externa', verbose_name='Observações')),
                ('ativa', models.BooleanField(default=True, help_text='Se a conta externa está ativa', verbose_name='Ativa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('sincronizado', models.BooleanField(default=False, help_text='Se a conta foi sincronizada com o sistema externo', verbose_name='Sincronizado')),
                ('data_ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronização')),
                ('conta_contabil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_externas', to='core.contacontabil', verbose_name='Conta Contábil Interna')),
            ],
            options={
                'verbose_name': 'Conta Externa',
                'verbose_name_plural': 'Contas Externas',
                'db_table': 'contas_externas',
                'ordering': ['conta_contabil__codigo', 'codigo_externo'],
                'indexes': [models.Index(fields=['conta_contabil'], name='contas_exte_conta_c_582c32_idx'), models.Index(fields=['codigo_externo'], name='contas_exte_codigo__d7eea9_idx'), models.Index(fields=['sistema_origem'], name='contas_exte_sistema_d41db3_idx'), models.Index(fields=['ativa'], name='contas_exte_ativa_f7c987_idx'), models.Index(fields=['sincronizado'], name='contas_exte_sincron_947a59_idx'), models.Index(fields=['codigo_externo', 'ativa'], name='contas_exte_codigo__271330_idx')],
                'unique_together': {('conta_contabil', 'codigo_externo', 'ativa')},
            },
        ),
        migrations.CreateModel(
            name='EmpresaCentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_vinculadas', to='core.centrocusto', verbose_name='Centro de Custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_custo_empresa', to='core.empresa', verbose_name='Empresa')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_custo_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_centro_custo_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Centro de Custo da Empresa',
                'verbose_name_plural': 'Centros de Custo das Empresas',
                'db_table': 'empresa_centros_custo',
                'ordering': ['empresa__sigla', 'centro_custo__codigo'],
                'indexes': [models.Index(fields=['empresa', 'ativo'], name='empresa_cen_empresa_b6434c_idx'), models.Index(fields=['centro_custo', 'ativo'], name='empresa_cen_centro__891f7d_idx'), models.Index(fields=['responsavel'], name='empresa_cen_respons_3b840e_idx'), models.Index(fields=['ativo'], name='empresa_cen_ativo_63c9c9_idx')],
                'unique_together': {('empresa', 'centro_custo', 'ativo')},
            },
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo'], name='unidades_codigo_a2b9f8_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo_pai'], name='unidades_codigo__ae00c8_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['codigo_allstrategy'], name='unidades_codigo__5b5acd_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['ativa'], name='unidades_ativa_6fd9a8_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['nivel'], name='unidades_nivel_8d5829_idx'),
        ),
        migrations.AddIndex(
            model_name='unidade',
            index=models.Index(fields=['empresa'], name='unidades_empresa_2d6101_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['ano', 'mes'], name='movimentos_ano_601055_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['periodo_mes_ano'], name='movimentos_periodo_3e19af_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data'], name='movimentos_data_60e054_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data', 'unidade'], name='movimentos_data_f31825_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['unidade'], name='movimentos_unidade_c19ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['centro_custo'], name='movimentos_centro__6a46ee_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['conta_contabil'], name='movimentos_conta_c_9297f1_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['fornecedor'], name='movimentos_fornece_b606f6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['natureza'], name='movimentos_naturez_328a78_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['valor'], name='movimentos_valor_441953_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['data_importacao'], name='movimentos_data_im_5ac41c_idx'),
        ),
        migrations.AddIndex(
            model_name='movimento',
            index=models.Index(fields=['arquivo_origem'], name='movimentos_arquivo_9fe715_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocentrocusto',
            unique_together={('usuario', 'centro_custo')},
        ),
    ]
